services:
  dev:
    build:
      context: .
      target: dev
    environment:
      MONGO_URI: mongodb://bookwormdb:27017
    ports:
      - 5000:5000
    depends_on:
      - bookwormdb
  test:
    build:
      context: .
      target: test
    environment:
      MONGO_URI: mongodb://bookwormdb:27017
    ports:
      - 3000:3000
    depends_on:
      - bookwormdb
    profiles:
      - test
  bookwormdb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
